config/routes.rb
Rails.application.routes.draw do
  root  'email_genaretor#index'
  match "new", to: "email_genaretor#index", via: :get
  get "about-us", to: "email_genaretor#about", as: :about
  get "your-profile", to: "email_genaretor#profile", as: :profile
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_genaretor_controller.rb
class EmailGenaretorController < ApplicationController
  def index
    @random_email = random_email
    if @random_email != '' 
      puts "You successfully genaret email"
    else
      puts "try agin"
    end
  end
  def random_email
    # Generate a random string for the local part of the email address
    local_part = (0...8).map { ('a'..'z').to_a[rand(26)] }.join
  
    # Generate a random domain name
    domains = ["example.com", "example.net", "example.org"]
    domain = domains.sample
  
    # Combine the local part and domain to create the email address
    email = "#{local_part}@#{domain}"
    
    return email
  end
  def about
  end
  def profile 
  end
  # Generate and print a random email address

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_genaretor_helper.rb
module EmailGenaretorHelper
end

app/views/email_genaretor/about.html.erb
<div class="position-relative mt-5 mb-4 ">
        <div class="position-absolute top-0 start-50 translate-middle">
            <%= @h="Author : Shiboshree Roy                                            " %><br>
            <%= @m="Version: 1.0.1                                                      "%><br>
            <%= @e=" Program :Temporary Email Genaretor                                 "%>
        </div>
</div>

app/views/email_genaretor/index.html.erb
<div class="row mt-5 mb-3">
    <span class="">
        <center><h1 >Email Genaretor </h1></center>
    </span>
    
</div>


<div class="card text-center">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">Your Email Address  </h5>
    <div class="card-text">
     <div class="col-auto" id="textarea">
        <%= @random_email %>
        <%= button_tag "Copy Text", id: "copy-button", class: "btn btn-outline-primary", data: { clipboard_target: "#email-content" } %>
      </div>

      </div>

    <%= link_to "Genaret Email", root_path, class: "btn btn-outline-success mt-2 "%>
  </div>
  <div class="card-footer text-body-secondary">
    <% require 'date' %>
    <% current_datetime = DateTime.now %>
    <% one_day_later = current_datetime + 1 %>
    <% one_week_earlier = current_datetime - 7 %>
    <%= current_datetime %>
  </div>
</div>

app/views/email_genaretor/profile.html.erb
<section class="vh-100" style="background-color: #9de2ff;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-md-9 col-lg-7 col-xl-5">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body p-4">
            <div class="d-flex text-black">
              <div class="flex-shrink-0">
               
                  <img src="https://cdn2.f-cdn.com/ppic/227678900/logo/71421622/IC2aT/CROPPED_profile_logo_PGYTA_12b1ac71f3498b4693e3836ff78cda10.jpeg?image-optimizer=force&format=webply&width=336"
                  alt="Generic placeholder image" class="img-fluid"
                  style="width: 180px; border-radius: 10px;">
              </div>
              <div class="flex-grow-1 ms-3">
                <h5 class="mb-1">Shiboshree Roy</h5>
                <p class="mb-2 pb-1" style="color: #2b2a2a;">Junior Full Stack Web Developer</p>
                <div class="d-flex justify-content-start rounded-3 p-2 mb-2"
                  style="background-color: #efefef;">
                  <div>
                    <p class="small text-muted mb-1">Projects</p>
                    <p class="mb-0">41</p>
                  </div>
                  <div class="px-3">
                    <p class="small text-muted mb-1">Followers</p>
                    <p class="mb-0">100M</p>
                  </div>
                  <div>
                    <p class="small text-muted mb-1">Rating</p>
                    <p class="mb-0">8.5</p>
                  </div>
                </div>
                <div class="d-flex pt-1">
                  <button type="button" class="btn btn-outline-primary me-1 flex-grow-1"><a href="https://www.facebook.com/profile.php?id=100074842707732">Chat</a></button>
                  <button type="button" class="btn btn-primary flex-grow-1">Follow</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/header/_nav.html.erb
<nav class="navbar bg bg-danger mt-3 mb-4 " style="border: 1px solid #fff; border-radius: 5px;">
  <div class="container-fluid">
    <%= link_to "Email Generator", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home",root_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
         <%= link_to"About",about_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Profile",profile_path, class: "nav-link active"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoActionMailerHelloWorld01</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'copy_button' %>
    


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
       <%= render 'header/nav' %>
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js"></script>

  </body>
</html>